name: yulli
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_dialog: ^0.9.3
  badges: ^1.1.1
  cached_network_image: ^2.2.0+1
  chewie: ^1.0.0
  cloud_firestore: ^1.0.1
  collection: ^1.14.13
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.0
  device_info: ^2.0.0
  device_preview: ^0.7.1
  devicelocale: ^0.2.3
  dotted_border: ^2.0.0-nullsafety.0
  email_validator: ^1.0.4
  eva_icons_flutter: ^2.0.0
  feather_icons_flutter: ^4.7.4
  file_picker: ^3.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_messaging: ^10.0.0
  firebase_storage: ^8.0.0
  fluro_fork: ^0.0.1
  flutter_datetime_picker: ^1.3.5
  flutter_html: ^2.0.0-nullsafety.0
  flutter_keyboard_visibility: ^5.0.0
  flutter_linkify: ^4.0.2
  flutter_local_notifications: ^5.0.0
  flutter_screenutil: ^1.1.0
  flutter_sheet_localization: ^3.0.0
  flutter_speed_dial: ^1.2.5
  flutter_spinkit: ^4.1.2+1
  flutter_svg: ^0.21.0-nullsafety.0
  fluttertoast: ^4.0.1
  freezed_annotation: ^0.12.0
  image_cropper: ^1.2.3
  image_picker: ^0.7.3
  intl: ^0.17.0-nullsafety.2
  introduction_screen: ^2.1.0
  logger: ^0.9.1
  material_design_icons_flutter: ^4.0.5345
  modal_bottom_sheet: ^1.0.0+1
  package_info: ^0.4.0+18
  percent_indicator: ^2.1.3
  permission_handler: ^6.1.1
  provider: ^5.0.0
  pull_to_refresh: 1.6.4
  regexpattern: ^0.2.3
  rxdart: ^0.24.0
  shared_preferences: ^2.0.4
  simple_animations: ^2.2.1
  sleek_circular_slider: ^1.1.0
  string_validator: ^0.1.4
  supercharged: ^1.6.0
  url_launcher: ^6.0.9
  uuid: ^3.0.0
  video_player: ^2.0.0
  wechat_camera_picker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.2
  flutter_sheet_localization_generator: ^3.0.0
  freezed: ^0.12.7
  json_serializable: ^3.3.0

dependency_overrides:
  analyzer: ^0.41.1
  freezed: ^0.12.7
  freezed_annotation: ^0.12.0
  json_annotation: ^4.0.0
  build: ^2.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway-BlackItalic.ttf
          weight: 900
          style: italic
